### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by FraLotito** [GiovanniForlenza/rusthypergraph#7]
Ciao Giovanni! 

I've stumbled upon this repo, it is a very interesting project! 

I'm currently working on something similar with one of my students, would you be interested in having a chat and exchange some ideas?

**Comment by GiovanniForlenza** [comment]
Ciao Francesco!
Thank you! We also have started working on this project as part of my thesis.
We would definitely be interested in having a chat, so we can arrange a meeting whenever you are available!
You can find my email in my profile, so feel free to write to me!
Hope to hear from you soon!
